/*
 * This file is generated by jOOQ.
 */
package com.gt.petcatalog.tables.records;


import com.gt.petcatalog.tables.Users;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public UsersRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.users.external_id</code>.
     */
    public UsersRecord setExternalId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.users.external_id</code>.
     */
    public UUID getExternalId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.users.name</code>.
     */
    public UsersRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.users.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.users.phone</code>.
     */
    public UsersRecord setPhone(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.users.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.users.email</code>.
     */
    public UsersRecord setEmail(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.users.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.users.address</code>.
     */
    public UsersRecord setAddress(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.users.address</code>.
     */
    public String getAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.users.region</code>.
     */
    public UsersRecord setRegion(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.users.region</code>.
     */
    public String getRegion() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.users.city</code>.
     */
    public UsersRecord setCity(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.users.city</code>.
     */
    public String getCity() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.users.state</code>.
     */
    public UsersRecord setState(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.users.state</code>.
     */
    public String getState() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.users.created_at</code>.
     */
    public UsersRecord setCreatedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.users.last_update</code>.
     */
    public UsersRecord setLastUpdate(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.users.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer id, UUID externalId, String name, String phone, String email, String address, String region, String city, String state, LocalDateTime createdAt, LocalDateTime lastUpdate) {
        super(Users.USERS);

        setId(id);
        setExternalId(externalId);
        setName(name);
        setPhone(phone);
        setEmail(email);
        setAddress(address);
        setRegion(region);
        setCity(city);
        setState(state);
        setCreatedAt(createdAt);
        setLastUpdate(lastUpdate);
        resetChangedOnNotNull();
    }
}
