/*
 * This file is generated by jOOQ.
 */
package com.gt.springtools;


import com.gt.springtools.tables.User;
import com.gt.springtools.tables.records.UserRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserRecord> USERS_EXTERNAL_ID_KEY = Internal.createUniqueKey(User.USER, DSL.name("users_external_id_key"), new TableField[] { User.USER.EXTERNAL_ID }, true);
    public static final UniqueKey<UserRecord> USERS_PKEY = Internal.createUniqueKey(User.USER, DSL.name("users_pkey"), new TableField[] { User.USER.ID }, true);
}
