/*
 * This file is generated by jOOQ.
 */
package com.gt.springtools;


import com.gt.springtools.tables.FlywaySchemaHistory;
import com.gt.springtools.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
